CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS Stories
  (story_id uuid PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
   title VARCHAR(128) NOT NULL DEFAULT 'Anonymous',
   author VARCHAR(128) NOT NULL DEFAULT 'Anonymous',
   date_added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   latitude FLOAT NOT NULL,
   longitude FLOAT NOT NULL,
   story VARCHAR(100000) NOT NULL,
   category VARCHAR(128) NOT NULL DEFAULT 'Misc'
  );
